### ISSUE TITLE
Docs unclear

### ISSUE THREAD

**Issue by jan-dh** [studioespresso/craft3-seeder#1]
I've followed the installation guide from the docs. I have the plugin installed, showing up as installed in the admin panel but I'm unable to get it working. With all the commands I try from the docs I keep getting  `unknown command "seeder/generate`

**Comment by janhenckens** [comment]
Hey Jan

Thanks for trying out the plugin!
When running `./craft help`, are the seeder commands listed there? 

If they are not, I think the issue is that your config can't connect to the database through the command line (so it can't read the installed plugins, so it doesn't know the commands). Could you check that?

Thanks
Jan

**Comment by jan-dh** [comment]
You are right, no  seeder commands to be found. I'm working locally with a remote DB, our default setup for new project.

**Comment by janhenckens** [comment]
Well, your default project setup will probably not work over CLI...

As a test, try changing the database name to something random and run `./craft help` again. You'll still see the same commands as before (those are in Craft & Yii itself), not the commands coming from plugins.

I don't know your exact setup but that's the reason you're not seeing the other commands.

**Comment by jan-dh** [comment]
Hmm, the issue is indeed related to the `./craft` not having access to the DB. As for the installing instructions, are you planning to put the plugin on the store? If I find some time i'll do a PR for some more beginner friendly docs this week.

**Comment by jan-dh** [comment]
Ok, so, seems that when you're using the Craft3-Multi-Environment setup, you should use `127.0.0.1` in your `.env.php` for your database setup,  instead of `localhost` - working with MAMP - to get access to the plugins. Got it working now.

**Comment by janhenckens** [comment]
Yes, it's definitely going on the plugin store, just making sure that everything works and is clear for people to use it. Will be adding a note about this to the docs too!
