### ISSUE TITLE
FR: add option to specify siteId

### ISSUE THREAD

**Issue by jan-dh** [studioespresso/craft3-seeder#14]
I would like to seed a section for one specific site that is not the main site. At the moment I'm getting an error

```
The section xxx is not enabled for the site '1'' 
```

Tried adding something like `--site="2"` or `--siteId="2"` but that doesn't seem to work:

```
Unknown option: --site
```

**Comment by janhenckens** [comment]
Good one! I don't think the queries that create elements in the plugin have any siteId set right now. Should be easy enough to add!

**Comment by janhenckens** [comment]
Hey @jan-dh, totally lost track of this one. Actually added it 3 weeks ago and now it's released as well :)
