### ISSUE TITLE
Issue when seeding entry with many fields/plugins

### ISSUE THREAD

**Issue by mylesthedev** [studioespresso/craft3-seeder#3]
I have an entry type that is using many fields which include a few plugins e.g. LinkField and ImageOptimize.

Should the seeder just skip those fields?

I ge the following error when sending:

```php Fieldtype not supported:LinkField
PHP Warning 'yii\base\ErrorException' with message 'A non-numeric value encountered'

in /home/vagrant/Code/talleys.co.nz/vendor/studioespresso/craft-seeder/src/services/fields/Fields.php:185
```

**Comment by jan-dh** [comment]
There is a list of supported field types. My guess is that more will be added later, but for now only use the available ones.

**Comment by janhenckens** [comment]
If all goes well, you should just see a notice in your terminal when the plugin encounters an unsupported field. 

But clearly not all is well :) Thanks for reporting this, I'll have a look tonight!

**Comment by janhenckens** [comment]
@mediabeastnz Could you confirm that you have a table field in the layout of the section that you're trying to seed here?

**Comment by janhenckens** [comment]
@mediabeastnz I released an update that should fix this issue, can you install that and give it another go? Thanks!

**Comment by mylesthedev** [comment]
Legend, thanks @janhenckens. I'll try it now and let you know

**Comment by mylesthedev** [comment]
Working now. I now get a notice saying field type not supported and it continues on through the loop.
