### ISSUE TITLE
Craft 3.1.0-beta7 incompatibility

### ISSUE THREAD

**Issue by smcyr** [studioespresso/craft3-seeder#5]
The plugin isn't working with Craft 3.1. The sources are now in uid format instead of id format. Here is the fix I did:
https://github.com/smcyr/craft3-seeder/commit/b45470bad45cb4fe9c318a67ec05ca65dc119474
Thanks!

**Comment by janhenckens** [comment]
Hey, can you submit this as a pull request? Happy to merge in your changes.

**Comment by smcyr** [comment]
Here it is!
https://github.com/studioespresso/craft3-seeder/pull/6
Thanks!

**Comment by janhenckens** [comment]
Merged & Craft 3.1 compatibility is out now!
