### ISSUE TITLE
Composer update does not pick-up plugin updates

### ISSUE THREAD

**Issue by jan-dh** [studioespresso/craft3-seeder#7]
Running `composer update` doesn't pick up any changes in the plugin. 

I'm currently on version `2.0.2`. The admin panel shows me the next releases: 

```
|  2.1.3 	|   21-3-2019	|   
|  2.1.2 	|   20-3-2019	|   
|  2.1.1 	|   20-3-2019	|   
|  2.1.0 	|   18-3-2019	|   
```

**Comment by janhenckens** [comment]
Hey @jan-dh, I think this belongs in the Navigate repo? :)

**Comment by jan-dh** [comment]
Woops, yes it does 😄,  I'll move it over there.
